# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2f713cdbb31b8ad8047684b8cdb63988495d9af1aa5010fa8bbd714bb27c46631163764d3bfc5a0c052af1f50acd0426cff42a4210a654a0c1b81df250fe464

test:
  secret_key_base: c243dde9b73adafb11827136a8039a5dfe75705343d512b3fcc44efea6900d5e29c1d6dab878c282cbd03b8c4c6e6574149cce3e588a9028a441f5c42a5bd6ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
